- color: fef2c0
  description: Author 可申请锁住当前讨论
  name: Locked
- color: 8D0C0E
  description: ""
  name: Alpine
- color: C5DEF5
  description: ""
  name: Apple App Store
- color: 7623FA
  description: ""
  name: benchmark
- color: "010501"
  description: ""
  name: CLI
- color: 7169D2
  description: ""
  name: Debian
- color: 3246A9
  description: ""
  name: Editor
- color: 4A325C
  description: ""
  name: Elixir
- color: "630406"
  description: ""
  name: Git
- color: BFD4F2
  description: ""
  name: Github
- color: "591111"
  description: ""
  name: Gitlab
- color: 0052CC
  description: ""
  name: Golang
- color: 006b75
  description: ""
  name: IDE
- color: E9B83F
  description: ""
  name: Java
- color: FBCA04
  description: ""
  name: JavaScript
- color: 4C4A27
  description: ""
  name: Linux
- color: AF9736
  description: ""
  name: Lua
- color: C5DEF5
  description: ""
  name: MacOS
- color: 2F6C1C
  description: ""
  name: NodeJS
- color: 9F4324
  description: ""
  name: Podcast
- color: 1D76DB
  description: ""
  name: Python
- color: 2D3B8B
  description: ""
  name: Racket
- color: "290303"
  description: ""
  name: Ruby
- color: F6CA54
  description: ""
  name: Rust
- color: 2F393C
  description: ""
  name: Shell
- color: B1C494
  description: ""
  name: Talks用户指南
- color: 0052CC
  description: ""
  name: TypeScript
- color: 102F4C
  description: ""
  name: Ubuntu
- color: 7195A3
  description: ""
  name: WASM
- color: 0052CC
  description: ""
  name: Windows
- color: E4A340
  description: ""
  name: Zig
- color: "008672"
  description: ""
  name: 前端
- color: 079A59
  description: ""
  name: 大数据
- color: 1D76DB
  description: ""
  name: 容器
- color: 53D1C6
  description: 争议已和解
  name: 已和解
- color: 4321F7
  description: ""
  name: 数据库
- color: C74443
  description: 此话题有争执，请以包容开放的心态去理解
  name: 有争执
- color: 599DD6
  description: 游戏开发相关
  name: 游戏
- color: 13FA32
  description: ""
  name: 算法
- color: 568C7C
  description: ""
  name: 绘图
- color: 3AA06A
  description: ""
  name: 网络工具
- color: D4CBCC
  description: ""
  name: 翻译
